spring:
  boot:
    admin:
#      client:
#        metadata:
#          user:
#            name: root
#            password: root
      monitor:
        period: 60000
      discovery:
        enabled: true
      notify:
        mail:
          to: xxxxxxxxx@qq.com
          from: xxxxxxxxx@sina.com
      turbine:
        clusters: default
        location: koo-cloud-server-monitor
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream,activiti
turbine:
  app-config: KOO-CLOUD-SERVER-GATEWAY,KOO-CLOUD-PROVIDER-UAC #所要监控的项目,注意必须大写
  cluster-name-expression: new String("default")

management:
  security:
    enabled: false
#  ui登录的用户名和密码信息    
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false
#eureka 的配置信息    
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka:8761/eureka/
  instance:
      lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: cloud-monitor  # 在信息列表时显示主机名称
      prefer-ip-address: true     # 访问的路径变为IP地址  

