server:
  port: 881
spring:
  cloud:
    stream:
      rabbit: 
        bindings:
          cloud_output:
            producer: # 进行生产端配置
              routing-key-expression: '''mldn-key'''
      bindings: # 服务的整合处理
        cloud_input: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: RKExchange # 表示要使用的Exchange名称定义
          content-type: application/json  # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: cloud-mqc
      binders:  #　在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit:  # 表示定义的名称，用于于binding整合
          type: rabbit  # 消息组件类型
          environment:  # 设置rabbitmq的相关的环境配置
            spring: 
              rabbitmq:
                addresses: rabbitmq-server
                username: root
                password: root
                virtual-host: /
  redis:
    host: redis-server
    password: wapvipwsk
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false           
info:
  owner: kingkoo1985@gmail.com
  version: 1.0.0        
logging:
  level:
    root: info
  path: logs/
  file: ${spring.application.name}.log