spring:  
  application:
    name: '@pom.artifactId@'
  profiles:
    active: '@profileActive@'  
info:
  owner: kingkoo1985@gmail.com
  version: $project.verson$     
  app.name: koo-cloud
  company.name: koo-cloud-company
  build.artifactId: $project.artifactId$
  build.version: $project.verson$     
#logging 配置信息
logging:
  level:
    root: info
  path: logs/
  file: ${spring.application.name}.log 