server:
  port: 8015
spring:
  application:
    name: KOO-CLOUD-SERVER-ZIPKIN
  rabbitmq:
    host: paascloud-mq-rabbit
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
  zipkin:    
    locator:
      discovery:
        enabled: true
management:
  security:
    enabled: false
info:
  owner: kingkoo1985@gmail.com
  version: 1.0.0
zipkin:
  storage:  # 设置zipkin收集的信息通过mysql进行存储
    type: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
logging:
  level:
    root: info
  path: logs/
  file: ${spring.application.name}.log
